#!/usr/bin/env python3
"""Generates the pinned CASE FOLDING table shared by the builder and the app.

    python3 tools/unicode/gen_casefold.py

## Why it exists, and why `lowercase()` is not enough

The code that names a sense (`payload.sense_code`) folds the gloss before hashing it, so that two
dictionaries writing the same definition in different case recognize it as the same one. The
operation the standard defines for that is **`toCaseFold()`** --rule R4, section 3.13 of the
Unicode Standard, referenced by UAX #31 as the operation for *caseless matching*-- and the
standard is explicit: `toLowerCase()` is **case mapping**, which serves to DISPLAY text;
`toCaseFold()` is **case folding**, which serves to COMPARE it.

`lowercase()` was being used. Measured over the pinned repertoire, **242 of 133,730 code points
(0.181 %)** give different results: `ß`→`ss`, `ſ`→`s`, `ς`→`σ`, `ͅ`→`ι`. Over the real glosses that
is 8 of 97,337 in Spanish and 19 of 162,820 in English -- `ß-endorfina`, `µm`, Greek text.

## Why a TABLE and not the platform's function

⚠️ **Python has `str.casefold()`; Java and Kotlin have no equivalent.** The only thing that offers
it is ICU, and **D-003 forbids the platform's Unicode data**: every Android ships its own version
and that classified 14,773 code points differently between watches. Using `android.icu` to fold
would reintroduce exactly the bug D-003 exists to prevent.

So the table is pinned, which is the same pattern `UnicodeRepertoire` already uses and for the
same reason: **both languages apply the SAME data**, and the sha256 ties the two copies together.

## Raising the version is a deliberate act

It aborts if the Python running it does not ship **exactly** the Unicode version the repertoire is
pinned to: a folding table from Unicode 16 against a repertoire from Unicode 13 would be a silent
inconsistency between two files that are read together.

⚠️ **And regenerating it invalidates every `sense_code` already written.** It carries the same
weight as bumping `NORM_VERSION`: it is done knowingly or it is not done.
"""

import hashlib
import os
import sys
import unicodedata

PINNED_UNICODE_VERSION = "13.0.0"

_AQUI = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(_AQUI, "casefold.txt")
KOTLIN_PATH = os.path.join(
    _AQUI, "..", "..", "dict-core", "src", "main", "kotlin", "cl", "fadiaz",
    "dictionary", "core", "CaseFolding.kt",
)


def compute_pairs():
    """`[(code_point, folded)]` for what `casefold()` does and `lower()` does not.

    Only the difference goes in: what `lower()` already resolves correctly needs no table, and
    including it would duplicate data the platform gives identically in both languages (D-004).
    """
    pares = []
    for cp in range(0x110000):
        ch = chr(cp)
        bajo, plegado = ch.lower(), ch.casefold()
        if bajo != plegado:
            pares.append((cp, plegado))
    return pares


def encode(pares):
    """`cp:folded` comma separated, the cp in base 16 and the folding in \\uXXXX escapes."""
    return ",".join(
        "%x:%s" % (cp, "".join("%04x" % ord(c) for c in plegado)) for cp, plegado in pares
    )


def main():
    actual = unicodedata.unidata_version
    if actual != PINNED_UNICODE_VERSION:
        print(
            "ERROR: this Python ships Unicode %s but the table is pinned to %s.\n"
            "Raising the version is deliberate: read this file's header."
            % (actual, PINNED_UNICODE_VERSION),
            file=sys.stderr,
        )
        return 1

    pares = compute_pairs()
    # ⚠️ The Kotlin side indexes by `Char` so as not to use the JVM APIs D-017 forbids in
    # :dict-core. That only holds if nothing falls outside the BMP, so it is checked here rather
    # than trusted: if Unicode ever adds a folding outside the BMP, this aborts and says so.
    fuera = [cp for cp, dest in pares
             if cp > 0xFFFF or any(ord(c) > 0xFFFF for c in dest)]
    if fuera:
        print("ERROR: %d pairs fall outside the BMP (%s...). The Kotlin side indexes by Char:\n"
              "they have to go back to code points and those APIs move to PlatformJvm.kt."
              % (len(fuera), ", ".join(hex(c) for c in fuera[:5])), file=sys.stderr)
        return 1
    blob = encode(pares)
    digest = hashlib.sha256(blob.encode("ascii")).hexdigest()

    with open(DATA_PATH, "w", encoding="ascii") as handle:
        handle.write(
            "# Pinned case folding table, generated by tools/unicode/gen_casefold.py.\n"
            "# DO NOT EDIT BY HAND. Read the generator's header to learn why it exists.\n"
            "#\n"
            "# It only carries what casefold() does and lower() does not: the rest is given\n"
            "# identically by both platforms and is measured (D-004). The sha256 ties this\n"
            "# copy to dict-core CaseFolding.kt.\n"
            "#\n"
            "unicode_version %s\n"
            "pairs %d\n"
            "sha256 %s\n"
            "data %s\n" % (PINNED_UNICODE_VERSION, len(pares), digest, blob)
        )

    _write_kotlin(blob, digest, len(pares))
    print("Case folding table pinned to Unicode %s" % PINNED_UNICODE_VERSION)
    print("  %d pairs · sha256 %s" % (len(pares), digest[:16]))
    print("  %s" % DATA_PATH)
    print("  %s" % KOTLIN_PATH)
    return 0


def _write_kotlin(blob, digest, pair_count):
    chunks = [blob[i : i + 100] for i in range(0, len(blob), 100)]
    literal = "\n".join('        "%s" +' % chunk for chunk in chunks).rstrip(" +")
    with open(KOTLIN_PATH, "w", encoding="utf-8") as handle:
        handle.write('''package cl.fadiaz.dictionary.core

// GENERATED FILE, by tools/unicode/gen_casefold.py -- DO NOT EDIT BY HAND.
// Source of truth: tools/unicode/casefold.txt
//
// Case folding: the operation the standard defines for *caseless matching* --rule R4, section
// 3.13 of the Unicode Standard-- and which is NOT `lowercase()`. The standard separates the two
// explicitly: case mapping serves to DISPLAY text, case folding to COMPARE it.
//
// ⚠️ It is a TABLE and not a platform call because Java and Kotlin **do not have**
// `toCaseFold()`: the only thing that offers it is ICU, and D-003 forbids the platform's Unicode
// data because every Android ships its own version --14,773 code points classified differently
// between watches. Pinning the table is the same pattern as UnicodeRepertoire, for the same
// reason.
//
// It only carries the %d code points where casefold() differs from lower(); the rest is given
// identically by both platforms and is measured (D-004).
//
// Pinned to Unicode %s. Regenerating invalidates every sense_code already written.
internal object CaseFolding {

    const val UNICODE_VERSION: String = "%s"

    /** sha256 of the encoded blob. Ties this copy to tools/unicode/casefold.txt. */
    const val DIGEST: String = "%s"

    const val PAIR_COUNT: Int = %d

    /** `cp:folded` in hexadecimal, comma separated. */
    internal const val ENCODED: String =
%s

    // ⚠️ **It indexes by `Char` and not by code point, and the generator verifies that**: none of
    // the pairs --neither source nor target-- falls outside the BMP. Iterating by char avoids
    // `Character.charCount` and `appendCodePoint`, which are JVM APIs and D-017 does not admit
    // them outside PlatformJvm.kt.
    private val mapa: Map<Char, String> = buildMap {
        for (entrada in ENCODED.split(',')) {
            val corte = entrada.indexOf(':')
            val origen = entrada.substring(0, corte).toInt(16).toChar()
            val destino = entrada.substring(corte + 1)
            val sb = StringBuilder()
            var i = 0
            while (i < destino.length) {
                sb.append(destino.substring(i, i + 4).toInt(16).toChar())
                i += 4
            }
            put(origen, sb.toString())
        }
    }

    /**
     * `toCaseFold()` over the pinned repertoire: lowercase first, then the table.
     *
     * `lowercase()` goes first because it resolves the vast majority of cases identically in both
     * languages (D-004, zero differences over 133,730 code points); the table corrects the %d
     * where the standard asks for something else.
     */
    fun fold(text: String): String {
        val bajo = text.lowercase()
        if (bajo.none { it in mapa }) return bajo
        val salida = StringBuilder(bajo.length)
        for (c in bajo) salida.append(mapa[c] ?: c)
        return salida.toString()
    }
}
''' % (pair_count, PINNED_UNICODE_VERSION, PINNED_UNICODE_VERSION, digest, pair_count,
       literal, pair_count))


if __name__ == "__main__":
    sys.exit(main())
